// PROBLEM 1 DAN 2
// MENCARI LUAS DAN KELILING DARI PERSEGI PANJANG
// CONTOH : PERSEGI PANJANG DENGAN PANJANG 5 DAN LEBAR 3

// NOTE
// RUMUS DARI LUAS PERSEGI PANJANG ADALAH PANJANG DIKALIKAN DENGAN LEBAR
// RUMUS DARI KELILING PERSEGI PANJANG ADALAH JUMLAH DARI PANJANG DAN LEBAR DIKALIKAN DUA

// PROBLEM BREAKDOWN
// MENCARI LUAS PERSEGI
// MASUKAN VALUE DARI PANJANG DAN LEBAR KE DALAM RUMUS LUAS PERSEGI PANJANG
// PANJANG (5) DIKALIKAN DENGAN LEBAR (3)

// MENCARI KELILING PERSEGI
// MASUKAN VALUE DARI PANJANG DAN LEBAR KE DALAM RUMUS KELILING PERSEGI PANJANG
// PANJANG DITAMBAH LEBAR, LALU DIKALIKAN DUA

const panjang: number = 5;
const lebar: number = 3;

const luasPersegiPanjang: number = (panjang * lebar);
console.log(luasPersegiPanjang);

const kelilingPersegiPanjang: number = ((panjang + lebar) * 2)
console.log(kelilingPersegiPanjang);

// PROBLEM 3
// MENCARI DIAMETER, KELILING DAN LUAS DARI LINGKARAN
// CONTOH : LINGKARAN DENGAN JARI - JARI 5

// NOTE
// DIAMETER ADALAH JARI - JARI DIKALIKAN DUA
// RUMUS DARI KELILING LINGKARAN ADALAH KONSTANTA PI (3,14..) DIKALIKAN DIAMETER
// RUMUS DARI LUAS LINGKARAN ADALAH KONSTANTA PI (3,14..) DIKALIKAN KUADRAT DARI JARI - JARI

// PROBLEM BREAKDOWN
// MENCARI DIAMTER LINGKARAN = JARI - JARI DIKALIKAN DUA

// MENCARI KELILING LINGKARAN = PI (3,14..) DIKALIKAN DIAMETER

// MENCARI LUAR LINGKARAN = PI (3.14..) DIKALIKAN KUADRAT JARI - JARI

const jariJari: number = 5;
const diameter: number = (jariJari * 2);
console.log(diameter);

const kelilingLingkaran: number = Math.PI * diameter;
console.log(kelilingLingkaran);

const luasLingkaran: number = Math.PI * (Math.pow(jariJari, 2));
console.log(luasLingkaran);

// PROBLEM 4
// MENCARI BESAR SALAH SATU SUDUT DARI SEGITIGA
// CONTOH : SEGITIGA DENGAN KEDUA SUDUTNYA SUDUT A 80 DERAJAT DAN SUDUT B 65 DERAJAT

// NOTE
// JUMLAH SEMUA SUDUT DARI SEGITIGA ADALAH 180 DERAJAT

// PROBLEM BREAKDOWN
// JUMLAH SELURUH SUDUT SEGITIGA ( 180 DERAJAT ) DIKURANGI JUMLAH DARI SUDUT YANG DIKETAHUI ( SUDUT A 80 DERAJAT DAN SUDUT B 65 DERAJAT)

const sudutA: number = 80
const sudutB: number = 65
const sudutC: number = 180 - (sudutA + sudutB);
console.log(sudutC);

// PROBLEM 5
// KONVERSI DARI HARI KE TAHUN BULAN TANGGAL
// CONTOH: 400 HARI = 1 TAHUN 1 BULAN 5 HARI

// NOTES
// 1. 1 TAHUN = 365 HARI
// 2. 1 BULAN = 30 HARI

// PROBLEM BREAKDOWN (CONTOH 400 HARI)
// 1. KONVERSI DARI TOTAL HARI MENJADI TAHUN
// // HINT 
// // 1. 400 HARI ADA 1 TAHUN
// // SOLUSI
// // 1. 400 HARI DIBAGI 1 TAHUN(365 HARI) DI BULATKAN KEBAWAH
// 
// 2. KONVERSI DARI SISA HARI YANG SUDAH DIAMBIL TAHUN MENJADI BULAN
// // HINT
// // 1. SISA HARI SETELAH DIKURANG OLEH 1 TAHUN(365) ADALAH 35
// // 2. 35 HARI ADA 1 BULAN
// // SOLUSI
// // 1. 400 HARI DI MODULO 1 TAHUN(365 HARI) UNTUK MENDAPATKAN 35 HARI
// // 2. 35 HARI DIBAGI DENGAN 1 BULAN (30 HARI) DIBULATKAN KEBAWAH
// 
// 3. KONVERSI DARI SISA HARI YANG SUDAH DIAMBIL TAHUN DAN BULAN MENJADI HARI
// // HINT
// // 1. SISA HARI SETELAH DIKURANG 1 TAHUN DAN 1 BULAN ADALAH 5 HARI
// // SOLUSI
// // 1. 400 HARI DIMODULO 1 TAHUN (365 HARI) KEMUDIAN DI MODULO 1 BULAN (30 HARI)

const days: number = 400;

const year: number = Math.floor(days / 365);
console.log(year);

const month: number = Math.floor((days % 365) / 30);
console.log(month);

const day: number = (days % 365) % 30;
console.log(day);

// PROBLEM 6
// MENCARI SELISIH HARI PADA DUA TANGGAL
// CONTOH : ANTARA TANGGAL 20 JANUARI 2022 DAN 22 JANUARI 2022

// NOTE
// KEDUA TANGGAL MASIH DALAM BULAN DAN TAHUN YANG SAMA

// PROBLEM BREAKDOWN
// MENCARI SELISIH DENGAN CARA MENGURANGI TANGGAL YANG BARU DENGAN TANGGAL YANG LAMA

const tanggalLama = new Date ("2022-01-20");
const tanggalBaru = new Date ("2022-01-22");
const perbedaanHari = tanggalBaru.getDay() - tanggalLama.getDay();
console.log(perbedaanHari)